$(function(){
    $(".imgW").hover(function(){
        $(this).find(".mengban").show();
        $(this).find(".inner_p").show();  
        $(this).find(".outW").removeClass("smaller").addClass("bigger");
        $(this).find(".p1").removeClass("fadeOutUp").addClass("fadeInDown");
        $(this).find(".p2").removeClass("fadeOutDown").addClass("fadeInUp");
    },function(){
        $(this).find(".outW").removeClass("bigger").addClass("smaller");
        $(this).find(".mengban").hide();
        $(this).find(".p1").removeClass("fadeInDown").addClass("fadeOutUp");
        $(this).find(".p2").removeClass("fadeInUp").addClass("fadeOutDown");
    })
})